### PR TITLE
Initial work porting to modern CMake

### PR DESCRIPTION
**Pull request by mrexodia**
Work in progress. Depends on the latest Z3 master and patched capstone with modern cmake installation support (not yet merged). This allows you to use Triton with `find_package(triton)` like this:

```
cmake "-DCMAKE_INSTALL_PREFIX=$(pwd)/../capstone/install;$(pwd)/../z3/install;$(pwd)/../Triton/install;$(pwd)/../boost/install" -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```

This will also allow people to consume Triton via vcpkg or Hunter.

Left to do:

- [ ] Get tests working (python)
- [ ] Fix PIN
- [ ] Windows support for PIN
- [ ] Restore ASAN/GCOV support via `CMakePresets.json`
- [ ] Fix CI

Any feedback welcome 🙂

### CODE REVIEW

**Comment by SweetVishnya** [comment]
Will your merge allow to specify customly built z3/capstone lib/include directories?

**Comment by mrexodia** [comment]
> Will your merge allow to specify customly built z3/capstone lib/include directories?

You are able to set the CMAKE_PREFIX_PATH to any location. So you can build+install z3/capstone in any location and point CMake there.

**Comment by JonathanSalwan** [comment]
Hey @mrexodia, thanks for this draft, looks good to me if we can move on a modern cmake design. However, i'm clearly not a cmake expert and i can't help you on those todo =/.

**Comment by mrexodia** [comment]
> Hey @mrexodia, thanks for this draft, looks good to me if we can move on a modern cmake design. However, i'm clearly not a cmake expert and i can't help you on those todo =/.

It would be good if you could find out what magic parts of the current cmake is actually being used and what is dead weight. I’ll work on the TODOs in my free time :)

**Comment by lallousx86** [comment]
@mrexodia CMake will be great especially if it makes Windows installation easier. Perhaps also make all Triton dependencies as submodules for git. Like this we can checkout one code base and get everything compiled in one go.

**Comment by mrexodia** [comment]
Yeah this is something I’ve been meaning to get back to but unfortunately life doesn’t want me to…

**Comment by JonathanSalwan** [comment]
@mrexodia, i've create a new branch (`dev-cmake`) forked from our current dev one (`dev-bitwuzla` which is forked from `dev-v0.9`) so that we have a good rebase of your PR from our dev. I've not fully merged it yet, my goal is to clean as much as possible our current cmake configuration based on your PR so that everything are working like before. Once it's done, we can start polishing the patch to improve cmake compile process for every platform.

**Comment by JonathanSalwan** [comment]
I'm closing this. I've rebased and merged it in `dev-cmake`. @mrexodia, i've commited your changes with your name (4d4107ea7fb9a11dabda656655d2ac2e8ac5df11 and 531cd53ad1a47dba18845a80f569145e27d7bc0a)

**Comment by mrexodia** [comment]
Thanks for picking this up! I hope to get back to it soon and review your changes.

Personally I was blocked on capstone not having proper CMake packaging upstream, I'll have to push this but I have a suspicion it won't be accepted.

**Pull request closed without merging**
