### PR TITLE
Symbolized pointers mode

### PR DESCRIPTION
**Pull request by SweetVishnya**
Added support for symbolic memory addresses. A special SYMBOLIZED_POINTERS mode is added. Memory is represented as a Z3 array. All memory reads/writes are implemented with corresponding selects/stores on this array.

New API for getMemoryAst is added as follows:
```
ctx.getMemoryAst(baseRegister, offset, size)  # [baseRegister+offset] of size
```

P.S. docs for getMemoryAst are not considered.

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
Interesting. It's been a while that I wanted to add array theory, so that's a really nice PR =). Let me few weeks to review that.

**Comment by SweetVishnya** [comment]
Why have you decided to close this pull request?

**Comment by JonathanSalwan** [comment]
mmmmh, I never wanted close the PR. Looks like all PRs has been closed... It's probably an automatic mechanism when pushing the new release and closing the dev-v0.6.

**Comment by kokole** [comment]
Hello, any news on this?

**Comment by JonathanSalwan** [comment]
@kokole I'm currently finishing a thesis that's why I have not so much time on Triton these last months, but when it's done I'm on this feature. It's not just merging this PR, it's about redesigning all the way we symbollically execute the memory.

**Comment by JonathanSalwan** [comment]
I don't know why I cannot reopen this MR and rebase it on dev-v0.8 but i'm on it. I will add this feature for the v0.8.

**Comment by SweetVishnya** [comment]
Symbolic memory model is quite similar to [BARF](https://github.com/programa-stic/barf-project/blob/master/doc/papers/barf.pdf) (section 3.2).
I have an example in [this presentation](https://vishnya.xyz/vishnyakov-isprasopen2018.pdf) (extra slides in the end).
Screenshot from 2019-10-02 12-58-53
Screenshot from 2019-10-02 12-59-08

If you have any further questions, feel free to ask.

**Comment by JonathanSalwan** [comment]
Thanks this model is clear in my mind. The main issue is about how we will handle `expr.evaluate()`

**Comment by anaivebird** [comment]
So these features are still not exist on release version until 2021/2/15?

**Comment by OMRI-FRX** [comment]
Ow ow ow ow,i need this feature

**Pull request closed without merging**
