### PR TITLE
Add tests for umov aarch64 instructions

### PR DESCRIPTION
**Pull request by psi-func**
+ Remove capstone 4.0.1 from CI

### CODE REVIEW

**Comment by psi-func** [comment]
sorry, `#ifdef` with capstone major version makes some instructions run incorrectly
+ add some tests for cmp unicorn and triton

**Comment by psi-func** [comment]
Wrote comment in previous [PR](https://github.com/JonathanSalwan/Triton/pull/1331#issuecomment-2137178057)
Found bug in capstone
Can fix it with additional logic in mov_s function semantics

**Comment by JonathanSalwan** [comment]
I think you should rebase on `dev-v1.0` and just push the fix of your `umov` semantic. Otherwise, we will have conflicts merging this one.

**Comment by psi-func** [comment]
> I think you should rebase on `dev-v1.0` and just push the fix of your `umov` semantic. Otherwise, we will have conflicts merging this one.

**Pull request closed without merging**
