### PR TITLE
Support capstone package with imported targets

### PR DESCRIPTION
**Pull request by theblackunknown**
## Description

This PR improves the CMake setup for the `capstone` whether it found using the embedded `FindCAPSTONE.cmake` or pull through an installed CMake config [1].
Moreover, I have added version extraction from header to get a log during configure to know which capstone version is being used.

[1] The `next` version of capstone is able to produce a CMake config described [here](https://github.com/capstone-engine/capstone/blob/c57915c8fd281b68ffa373fa646251fda552e38f/CMakeLists.txt#L645-L660).
This is being used when we want to build and install Triton through a package manager tool like [microsoft/vcpkg](https://github.com/microsoft/vcpkg)

### CODE REVIEW

**Comment by mrexodia** [comment]
Same here, deleting the custom find logic will work for the latest capstone version (eventually)

**Comment by SweetVishnya** [comment]
This PR and #1116 break specifying custom dependencies location:

```
CMake Error at CMakeModules/FindCAPSTONE.cmake:55 (find_file):
  Could not find CAPSTONE_VERSION_HEADER using the following files:
  capstone/capstone.h
Call Stack (most recent call first):
  CMakeLists.txt:136 (find_package)
```

**Comment by JonathanSalwan** [comment]
> Same here, deleting the custom find logic will work for the latest capstone version (eventually)

We will do that when your [PR](https://github.com/capstone-engine/capstone/pull/1841) will be in a packet release (v5?).

**Comment by SweetVishnya** [comment]
> This PR and #1116 break specifying custom dependencies location:
> 
> ```
> CMake Error at CMakeModules/FindCAPSTONE.cmake:55 (find_file):
>   Could not find CAPSTONE_VERSION_HEADER using the following files:
>   capstone/capstone.h
> Call Stack (most recent call first):
>   CMakeLists.txt:136 (find_package)
> ```

However, [PackageName_ROOT](https://cmake.org/cmake/help/latest/variable/PackageName_ROOT.html#packagename-root) may solve it.

**Comment by theblackunknown** [comment]
> This PR and #1116 break specifying custom dependencies location:
> 
> ```
> CMake Error at CMakeModules/FindCAPSTONE.cmake:55 (find_file):
>   Could not find CAPSTONE_VERSION_HEADER using the following files:
>   capstone/capstone.h
> Call Stack (most recent call first):
>   CMakeLists.txt:136 (find_package)
> ```

Indeed, we should be flexible and search for `capstone.h` whether it is directly accessible or accessible through `capstone` subfolder.

**Comment by SweetVishnya** [comment]
I specify capstone libs and includes via -DCAPSTONE_LIBRARIES and -DCAPSTONE_INCLUDE_DIRS.

**Comment by theblackunknown** [comment]
> I specify capstone libs and includes via -DCAPSTONE_LIBRARIES and -DCAPSTONE_INCLUDE_DIRS.

I see the `find_file` will fail as I do not take into account `CAPSTONE_INCLUDE_DIRS`.
I'll push a fix right now for this

**Comment by theblackunknown** [comment]
@SweetVishnya same here as my comment in #1116 
Can you give it one more try and let me know if this PR is in a good shape ?

**Pull request merged**
