### PR TITLE
Force to use python3 binary

### PR DESCRIPTION
**Pull request by XVilka**
Some distributions do not set `/usr/bin/python` if only python3 is installed, for example Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970375

I tried to compile Triton in this environment (Debian Sid and python3-only) and it fails due to `/usr/bin/env: 'python': No such file or directory`. At this point it's better to use `python3` binary explicitly.

- https://wiki.debian.org/Python/2Removal
- https://access.redhat.com/solutions/4455511
- https://pythonclock.org/

### CODE REVIEW

**Comment by SweetVishnya** [comment]
Hmm, interesting, I thought pin was working only with python 2.

**Comment by JonathanSalwan** [comment]
> Hmm, interesting, I thought pin was working only with python 2.

Yes, @XVilka you have to keep `python2` for every Pin script (` src/examples/pin/*`)

**Comment by XVilka** [comment]
Right, forgot about that 🤦

**Comment by XVilka** [comment]
Updated the PR.

**Pull request merged**
