### PR TITLE
Remove duplicate find python code

### PR DESCRIPTION
**Pull request by bananaappletw**
I think this line should be redundant, maybe.
I am not sure, I haven't read all of `cmake` related code.
If I am wrong, correct me.
Thanks.

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
cc @pbrunet

**Comment by pbrunet** [comment]
I would say there are no duplications as we check here for the interpreter while previous check is about libpython but @bananaappletw looks to have a better knowledge that me on this kind of think. May be I am wrong?

**Comment by bananaappletw** [comment]
@JonathanSalwan 
@pbrunet 
Sorry, my mistake.
I mistaken `PythonLibs` to `PythonInterp`.
This line can't be remove.
I think this line should move to `/CMakeLists.txt`.
Maybe for better consistency?

**Comment by bananaappletw** [comment]
@pbrunet 
Also, I think https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/CMakeLists.txt#L290
should be written as `setup.py` for better structure?

**Comment by bananaappletw** [comment]
I just try to write `setup.py` in `bindings/python` directory.
But it seems to be difficult, many dependency are missing.
The ideal situation is like I am at `bindings/python` directory.
Type `python setup.py install`.
Then `triton` package is installed.

**Comment by pbrunet** [comment]
You may have a look at : https://github.com/pbrunet/Triton/commit/4cff44f0b7e3c808784fae0b694fb6969fec1dca

It works correctly on linux but, as I am not a windows expert, I didn't succeed to make it works on windows.

There are multiple issue : 
1. Python library should link with the same crt than cpython and python2.7 was compiled using MSVC 2008 on  windows which don't support modern c++. But we live dangerously and hope the CRT didn't change to much...
2. setup.py will create a triton.so which link with libtriton.so. It is ok on linux but with windows, you have to export symboles from libtriton.dll (__declspec(dllimport)) and here I didn't succeed to make it works because of multiple crt linkage.

**Comment by bananaappletw** [comment]
@pbrunet 
Thanks for the great explanation.
I want to do the same thing as you did then.
Maybe I will meet those issues, too.
Since that's hard to do that.
Maybe, I make `triton` support `python3` first?
Could you also checkout [this](https://github.com/JonathanSalwan/Triton/pull/527)?
This pull request move python code to the same place, just for better management.
Thanks.

**Comment by pbrunet** [comment]
I really hope you will succeed to do it. I guess you will need to search an option that ask to export every symbole as std::string for example have to be exported.

I think python3 support and setup.py are not related. So you can do it in any order. The main issue will be about the python capi which should be adapted for some corner cases and guarded by python version preprocessor option.

One of the main benefit from using python3 will be to use modern msvc compiler with the setup but for compatibility, python2.7 support should still be available.

**Comment by bananaappletw** [comment]
@pbrunet 
I think I could refactor some `cmake` related code.
Then latter work should be easier to proceed.
Thanks for the information you provided.

**Comment by bananaappletw** [comment]
Actually, refactor to `setup.py` is more complicated than I thought.
I tried in recent days and found `cmake` is much simpler to dealing with it.

**Pull request closed without merging**
