### PR TITLE
Add AST optimizations

### PR DESCRIPTION
**Pull request by SweetVishnya**
Reopened
#712

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
Just to let you know, today I tested your PR adding a new mode (`SYMBOLIC_OPTIMIZATIONS`) and it seems that we loose some symbolic reasoning.

Tested patch below. Basically this patch just add a new mode (`SYMBOLIC_OPTIMIZATIONS`) and applies your optimizations if the mode is enabled. Then, I added some tests into our `test_simulation.py` file using this mode and some examples does not work with the mode enabled. If I find some time this week I will try to determine why we lost the symbolic reasoning.

```patch
diff --git a/src/libtriton/api/api.cpp b/src/libtriton/api/api.cpp
index 8a023101..7f838afd 100644
--- a/src/libtriton/api/api.cpp
+++ b/src/libtriton/api/api.cpp
@@ -224,7 +224,7 @@ Note that only the version `71313` of Pin is supported.
 
 namespace triton {
 
-  API::API() : callbacks(*this), arch(&this->callbacks), modes(), astCtxt() {
+  API::API() : callbacks(*this), arch(&this->callbacks), modes(), astCtxt(this->modes) {
   }
 
 
@@ -460,7 +460,7 @@ namespace triton {
     this->modes = triton::modes::Modes();
 
     // Clean up the ast context
-    this->astCtxt = triton::ast::AstContext();
+    this->astCtxt = triton::ast::AstContext(this->modes);
   }
 
 
diff --git a/src/libtriton/ast/astContext.cpp b/src/libtriton/ast/astContext.cpp
index 2eb00897..92a2b7f7 100644
--- a/src/libtriton/ast/astContext.cpp
+++ b/src/libtriton/ast/astContext.cpp
@@ -8,19 +8,22 @@
 #include <triton/ast.hpp>
 #include <triton/astContext.hpp>
 #include <triton/exceptions.hpp>
+#include <triton/modes.hpp>
 
 
 
 namespace triton {
   namespace ast {
 
-    AstContext::AstContext() {
+    AstContext::AstContext(triton::modes::Modes& modes)
+      : modes(modes) {
     }
 
 
     AstContext::AstContext(const AstContext& other)
       : astRepresentation(other.astRepresentation),
-        valueMapping(other.valueMapping) {
+        valueMapping(other.valueMapping),
+        modes(other.modes) {
     }
 
 
@@ -32,6 +35,7 @@ namespace triton {
     AstContext& AstContext::operator=(const AstContext& other) {
       this->astRepresentation = other.astRepresentation;
       this->valueMapping = other.valueMapping;
+      this->modes = other.modes;
       return *this;
     }
 
@@ -55,6 +59,15 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvadd(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: If we add zero, just return other expr */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return expr2;
+
+        if (!expr2->isSymbolized() && expr2->evaluate() == 0)
+          return expr1;
+      }
+
       SharedAbstractNode node = std::make_shared<BvaddNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -64,6 +77,19 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvand(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if we AND with zero -> return zero */
+        if ((!expr1->isSymbolized() && expr1->evaluate() == 0) || (!expr2->isSymbolized() && expr2->evaluate() == 0))
+          return this->bv(0, expr1->getBitvectorSize());
+
+        /* Optimization: if we AND with -1 -> return expr */
+        if (!expr2->isSymbolized() && ((~(expr2->evaluate()) & expr2->getBitvectorMask()) == 0))
+          return expr1;
+
+        if (!expr1->isSymbolized() && ((~(expr1->evaluate()) & expr1->getBitvectorMask()) == 0))
+          return expr2;
+      }
+
       SharedAbstractNode node = std::make_shared<BvandNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -73,6 +99,16 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvashr(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if expr1 == 0 -> return 0 */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return this->bv(0, expr1->getBitvectorSize());
+
+        /* Optimization: if expr2 == 0 -> return expr1 */
+        if (!expr2->isSymbolized() && expr2->evaluate() == 0)
+          return expr1;
+      }
+
       SharedAbstractNode node = std::make_shared<BvashrNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -91,6 +127,20 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvlshr(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if expr1 == 0 -> return 0 */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return this->bv(0, expr1->getBitvectorSize());
+
+        /* Optimization: if expr2 == 0 -> return expr1 */
+        if (!expr2->isSymbolized() && expr2->evaluate() == 0)
+          return expr1;
+
+        /* Optimization: if expr2 >= expr1.size -> return 0 */
+        if (!expr2->isSymbolized() && expr2->evaluate() >= expr1->getBitvectorSize())
+          return this->bv(0, expr1->getBitvectorSize());
+      }
+
       SharedAbstractNode node = std::make_shared<BvlshrNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -100,6 +150,19 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvmul(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: If we multiply with zero, just return zero */
+        if ((!expr1->isSymbolized() && expr1->evaluate() == 0) || (!expr2->isSymbolized() && expr2->evaluate() == 0))
+          return this->bv(0, expr1->getBitvectorSize());
+
+        /* Optimization: If we multiply with one, just return other expr */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 1)
+          return expr2;
+
+        if (!expr2->isSymbolized() && expr2->evaluate() == 1)
+          return expr1;
+      }
+
       SharedAbstractNode node = std::make_shared<BvmulNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -145,6 +208,22 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvor(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if we ior with 0 -> return other */
+        if (!expr2->isSymbolized() && expr2->evaluate() == 0)
+          return expr1;
+
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return expr2;
+
+        /* Optimization: if we OR with -1 -> return -1 */
+        if (!expr1->isSymbolized() && expr1->evaluate() == expr1->getBitvectorMask())
+          return this->bv(expr1->getBitvectorMask(), expr1->getBitvectorSize());
+
+        if (!expr2->isSymbolized() && expr2->evaluate() == expr2->getBitvectorMask())
+          return this->bv(expr2->getBitvectorMask(), expr2->getBitvectorSize());
+      }
+
       SharedAbstractNode node = std::make_shared<BvorNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -154,6 +233,12 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvrol(triton::uint32 rot, const SharedAbstractNode& expr) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if rot % expr.size == 0 -> return expr */
+        if ((rot % expr->getBitvectorSize()) == 0)
+          return expr;
+      }
+
       SharedAbstractNode node = std::make_shared<BvrolNode>(rot, expr);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -163,6 +248,16 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvrol(const SharedAbstractNode& rot, const SharedAbstractNode& expr) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if rot % expr.size == 0 -> return expr */
+        if (!rot->isSymbolized() && (rot->evaluate() % expr->getBitvectorSize()) == 0)
+          return expr;
+
+        /* Optimization: if expr == 0 or expr == -1 -> return expr */
+        if (!expr->isSymbolized() && (expr->evaluate() == 0 || (expr->evaluate() == expr->getBitvectorMask())))
+          return expr;
+      }
+
       SharedAbstractNode node = std::make_shared<BvrolNode>(rot, expr);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -172,6 +267,12 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvror(triton::uint32 rot, const SharedAbstractNode& expr) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if rot % expr.size == 0 -> return expr */
+        if ((rot % expr->getBitvectorSize()) == 0)
+          return expr;
+      }
+
       SharedAbstractNode node = std::make_shared<BvrorNode>(rot, expr);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -181,6 +282,16 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvror(const SharedAbstractNode& rot, const SharedAbstractNode& expr) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if rot % expr.size == 0 -> return expr */
+        if (!rot->isSymbolized() && (rot->evaluate() % expr->getBitvectorSize()) == 0)
+          return expr;
+
+        /* Optimization: if expr == 0 or expr == -1 -> return expr */
+        if (!expr->isSymbolized() && (expr->evaluate() == 0 || (expr->evaluate() == expr->getBitvectorMask())))
+          return expr;
+      }
+
       SharedAbstractNode node = std::make_shared<BvrorNode>(rot, expr);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -190,6 +301,12 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvsdiv(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if expr2 = 1 -> return expr1  */
+        if (!expr2->isSymbolized() && expr2->evaluate() == 1)
+          return expr1;
+      }
+
       SharedAbstractNode node = std::make_shared<BvsdivNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -217,6 +334,20 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvshl(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if expr1 = 0 -> return 0 */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return this->bv(0, expr1->getBitvectorSize());
+
+        /* Optimization: if expr2 = 0 -> return expr1 */
+        if (!expr2->isSymbolized() && expr2->evaluate() == 0)
+          return expr1;
+
+        /* Optimization: if expr2 >= expr1.size -> return 0 */
+        if (!expr2->isSymbolized() && expr2->evaluate() >= expr1->getBitvectorSize())
+          return this->bv(0, expr1->getBitvectorSize());
+      }
+
       SharedAbstractNode node = std::make_shared<BvshlNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -262,6 +393,16 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvsub(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if expr2 == 0 -> return expr1 */
+        if (!expr2->isSymbolized() && expr2->evaluate() == 0)
+          return expr1;
+
+        /* Optimization: if expr1 == 0 -> return expr2 */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return expr2;
+      }
+
       SharedAbstractNode node = std::make_shared<BvsubNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -280,6 +421,12 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvudiv(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if expr2 = 1 -> return expr1  */
+        if (!expr2->isSymbolized() && expr2->evaluate() == 1)
+          return expr1;
+      }
+
       SharedAbstractNode node = std::make_shared<BvudivNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -325,6 +472,12 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvurem(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if expr2 == 1 -> return 0 */
+        if (!expr2->isSymbolized() && (expr2->evaluate() == 1))
+          return this->bv(0, expr2->getBitvectorSize());
+      }
+
       SharedAbstractNode node = std::make_shared<BvuremNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
@@ -343,6 +496,15 @@ namespace triton {
 
 
     SharedAbstractNode AstContext::bvxor(const SharedAbstractNode& expr1, const SharedAbstractNode& expr2) {
+      if (this->modes.isModeEnabled(triton::modes::SYMBOLIC_OPTIMIZATIONS)) {
+        /* Optimization: if we XOR with 0 -> result is other expr */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return expr2;
+
+        if (!expr2->isSymbolized() && expr2->evaluate() == 0)
+          return expr1;
+      }
+
       SharedAbstractNode node = std::make_shared<BvxorNode>(expr1, expr2);
       if (node == nullptr)
         throw triton::exceptions::Ast("Node builders - Not enough memory");
diff --git a/src/libtriton/bindings/python/namespaces/initModeNamespace.cpp b/src/libtriton/bindings/python/namespaces/initModeNamespace.cpp
index d8b17918..9deb253d 100644
--- a/src/libtriton/bindings/python/namespaces/initModeNamespace.cpp
+++ b/src/libtriton/bindings/python/namespaces/initModeNamespace.cpp
@@ -43,6 +43,9 @@ Enabled, Triton will perform symbolic execution only on tainted instructions.
 - **MODE.PC_TRACKING_SYMBOLIC**<br>
 Enabled, Triton will track path constraints only if they are symbolized. This mode is enabled by default.
 
+- **MODE.SYMBOLIC_OPTIMIZATIONS**<br>
+Enabled, Triton will perform symbolic optimizations to reduce expressions complexity.
+
 - **MODE.TAINT_THROUGH_POINTERS**<br>
 Enabled, the taint is spread if an index pointer is already tainted (see #725).
 */
@@ -58,6 +61,7 @@ namespace triton {
         xPyDict_SetItemString(modeDict, "ONLY_ON_SYMBOLIZED",     PyLong_FromUint32(triton::modes::ONLY_ON_SYMBOLIZED));
         xPyDict_SetItemString(modeDict, "ONLY_ON_TAINTED",        PyLong_FromUint32(triton::modes::ONLY_ON_TAINTED));
         xPyDict_SetItemString(modeDict, "PC_TRACKING_SYMBOLIC",   PyLong_FromUint32(triton::modes::PC_TRACKING_SYMBOLIC));
+        xPyDict_SetItemString(modeDict, "SYMBOLIC_OPTIMIZATIONS", PyLong_FromUint32(triton::modes::SYMBOLIC_OPTIMIZATIONS));
         xPyDict_SetItemString(modeDict, "TAINT_THROUGH_POINTERS", PyLong_FromUint32(triton::modes::TAINT_THROUGH_POINTERS));
       }
 
diff --git a/src/libtriton/includes/triton/astContext.hpp b/src/libtriton/includes/triton/astContext.hpp
index df52315a..8e977bd4 100644
--- a/src/libtriton/includes/triton/astContext.hpp
+++ b/src/libtriton/includes/triton/astContext.hpp
@@ -12,6 +12,7 @@
 #include <triton/astRepresentation.hpp>   // for AstRepresentation, astRepre...
 #include <triton/dllexport.hpp>
 #include <triton/exceptions.hpp>
+#include <triton/modes.hpp>
 
 #include <map>
 #include <vector>
@@ -49,9 +50,12 @@ namespace triton {
         //! Map a concrete value and ast node for a variable name.
         std::map<std::string, std::pair<triton::ast::SharedAbstractNode, triton::uint512>> valueMapping;
 
+        //! Modes API.
+        triton::modes::Modes& modes;
+
       public:
         //! Constructor
-        TRITON_EXPORT AstContext();
+        TRITON_EXPORT AstContext(triton::modes::Modes& modes);
 
         //! Constructor by copy
         TRITON_EXPORT AstContext(const AstContext& other);
diff --git a/src/libtriton/includes/triton/modes.hpp b/src/libtriton/includes/triton/modes.hpp
index 93428b54..18eb4839 100644
--- a/src/libtriton/includes/triton/modes.hpp
+++ b/src/libtriton/includes/triton/modes.hpp
@@ -34,6 +34,7 @@ namespace triton {
       ONLY_ON_SYMBOLIZED,     //!< [symbolic mode] Perform symbolic execution only on symbolized expressions.
       ONLY_ON_TAINTED,        //!< [symbolic mode] Perform symbolic execution only on tainted instructions.
       PC_TRACKING_SYMBOLIC,   //!< [symbolic mode] Track path constraints only if they are symbolized.
+      SYMBOLIC_OPTIMIZATIONS, //!< [symbolic mode] Perform symbolic optimizations to reduce expressions complexity.
       TAINT_THROUGH_POINTERS, //!< [taint mode] Spread the taint if an index pointer is already tainted (see #725).
     };
 
diff --git a/src/libtriton/modes/modes.cpp b/src/libtriton/modes/modes.cpp
index c7c256ef..7e8e683e 100644
--- a/src/libtriton/modes/modes.cpp
+++ b/src/libtriton/modes/modes.cpp
@@ -49,4 +49,3 @@ namespace triton {
 
   }; /* modes namespace */
 }; /*triton namespace */
-
diff --git a/src/testers/unittests/test_simulation.py b/src/testers/unittests/test_simulation.py
index 245a9cbb..7f60d96f 100644
--- a/src/testers/unittests/test_simulation.py
+++ b/src/testers/unittests/test_simulation.py
@@ -391,6 +391,18 @@ class TestSymbolicEngineNoOptim(BaseTestSimulation, unittest.TestCase):
         super(TestSymbolicEngineNoOptim, self).setUp()
 
 
+class TestSymbolicEngineSymOpti(BaseTestSimulation, unittest.TestCase):
+
+    """Testing the symbolic emulation engine without optimization."""
+
+    def setUp(self):
+        """Define the arch."""
+        self.Triton = TritonContext()
+        self.Triton.setArchitecture(ARCH.X86_64)
+        self.Triton.enableMode(MODE.SYMBOLIC_OPTIMIZATIONS, True)
+        super(TestSymbolicEngineSymOpti, self).setUp()
+
+
 class TestSymbolicEngineAligned(BaseTestSimulation, unittest.TestCase):
 
     """Testing the symbolic emulation engine with ALIGNED_MEMORY."""
@@ -403,6 +415,19 @@ class TestSymbolicEngineAligned(BaseTestSimulation, unittest.TestCase):
         super(TestSymbolicEngineAligned, self).setUp()
 
 
+class TestSymbolicEngineAlignedSymOpti(BaseTestSimulation, unittest.TestCase):
+
+    """Testing the symbolic emulation engine with ALIGNED_MEMORY."""
+
+    def setUp(self):
+        """Define the arch and modes."""
+        self.Triton = TritonContext()
+        self.Triton.setArchitecture(ARCH.X86_64)
+        self.Triton.enableMode(MODE.ALIGNED_MEMORY, True)
+        self.Triton.enableMode(MODE.SYMBOLIC_OPTIMIZATIONS, True)
+        super(TestSymbolicEngineAlignedSymOpti, self).setUp()
+
+
 class TestSymbolicEngineAlignedAndTaintPtr(BaseTestSimulation, unittest.TestCase):
 
     """Testing the symbolic emulation engine with ALIGNED_MEMORY."""
@@ -441,6 +466,20 @@ class TestSymbolicEngineAlignedOnlySymbolized(BaseTestSimulation, unittest.TestC
         super(TestSymbolicEngineAlignedOnlySymbolized, self).setUp()
 
 
+class TestSymbolicEngineAlignedOnlySymbolizedSymOpti(BaseTestSimulation, unittest.TestCase):
+
+    """Testing the symbolic emulation engine with ALIGNED_MEMORY, ONLY_ON_SYMBOLIZED and SYMBOLIC_OPTIMIZATIONS."""
+
+    def setUp(self):
+        """Define the arch and modes."""
+        self.Triton = TritonContext()
+        self.Triton.setArchitecture(ARCH.X86_64)
+        self.Triton.enableMode(MODE.ALIGNED_MEMORY, True)
+        self.Triton.enableMode(MODE.ONLY_ON_SYMBOLIZED, True)
+        self.Triton.enableMode(MODE.SYMBOLIC_OPTIMIZATIONS, True)
+        super(TestSymbolicEngineAlignedOnlySymbolizedSymOpti, self).setUp()
+
+
 class TestSymbolicEngineDisable(BaseTestSimulation, unittest.TestCase):
 
     """Testing the emulation with the symbolic engine disabled."""
```

**Comment by SweetVishnya** [comment]
My student says that bitvector shifts might `evalute` incorrectly. I'll check that next time I see him.

**Comment by MAKI1LOVE** [comment]
You should remove the second optimization from bvsub
/* Optimization: if expr1 == 0 -> return expr2 */
+        if (!expr1->isSymbolized() && expr1->evaluate() == 0)
+          return expr2;
cause the result is -1*expr2

**Comment by MAKI1LOVE** [comment]
also these optimizations work incorrectly

        /* Optimization: if rot % expr.size == 0 -> return expr */
        if (!rot->isSymbolized() && (rot->evaluate() % expr->getBitvectorSize()) == 0)
          return expr;

        /* Optimization: if rot % expr.size == 0 -> return expr */
        if (!rot->isSymbolized() && (rot->evaluate() % expr->getBitvectorSize()) == 0)
          return expr;

from bvror and bvrol

**Comment by JonathanSalwan** [comment]
Merged into `dev-v0.7`

**Pull request closed without merging**
