### PR TITLE
AST optimization for ite node: True ? A : B => A, False ? A : B => B

### PR DESCRIPTION
**Pull request by SweetVishnya**
Simplify constant ite condition.

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
I think it's more a `CONSTANT_FOLDING` mode than an `AST_OPTIMIZATION`? We should maybe refactor [these lines](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/ast/astContext.cpp#L850-L854)? (i do not remember why i did this: `node->isLogical() == false`)

**Comment by SweetVishnya** [comment]
Can I enable it for both modes cause we do not use `CONSTANT_FOLDING`?

Maybe we can just remove [those lines](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/ast/astContext.cpp#L850-L854)? Because constants for then and else should be already folded by the time.

**Comment by RobinDavid** [comment]
Thanks @SweetVishnya . Yes it would be nice to have it in both mode. The difference between AST_OPTIMIZATION and CONSTANT_FOLDING is rather tight..

**Comment by SweetVishnya** [comment]
Fixed review issues in new commit

**Pull request merged**
