### PR TITLE
Python3 support for bindings

### PR DESCRIPTION
**Pull request by Oloshka**
It's a fix for #521 issue.

I tested it with examples from src/examples/python/. It seems that they work just like with python2.

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
Let us few weeks to review all the code.

**Comment by JonathanSalwan** [comment]
Can you please rebase from `dev-v0.6`?. I think there is a conflict around `initAstNodeNamespace.cpp`.

**Comment by Oloshka** [comment]
Yes, sure.

These changes are not clean because of plenty ifdefs. Maybe you can suggest how to do it more elegant way and test more intensively.

**Comment by JonathanSalwan** [comment]
I've merged your branch into our new `dev-py3` branch in order to perform tests in an easy way. I will also think about those ifdefs things and come back to you for feedback. When it's ok i will merge this `dev-py3` branch into `dev-v0.6`.

Thanks for this PR!

**Comment by TehRick** [comment]
Oloshka I made a python3-2 compatible fork but without updating the testing .py files. I don't use so many ifdefs: https://github.com/TehRick/Triton
It's about 310 additions and 121 deletions for the c side.

**Comment by JonathanSalwan** [comment]
Something cool will be to use `pybind11` for py2 and py3 compatibility and avoid the `incref` maintenance.

**Comment by TehRick** [comment]
Damn, I started doing it, I fetched, you did it --'

**Comment by JonathanSalwan** [comment]
Erf sorry @TehRick... Yes I started the binding yesterday and my progress is in the `dev-pybind11` branch =/

**Comment by JonathanSalwan** [comment]
Thanks for your `multiprecision_type_caster` at the end we will polish the code :)

**Comment by JonathanSalwan** [comment]
Ok. after some tests, it looks like `pybind11` consumes more memory and are slower than `cpython`. The memory consumption are may be my fault, i'm novice with `pybind11`. Anyway, atm i don't if moving forward on `pybind11` are the best solution...

**Comment by JonathanSalwan** [comment]
btw, @TehRick, can you rebase on `dev-v0.7` and make a PR of your `py3` changes?

**Comment by TehRick** [comment]
I have rebased but I am gonna fix today some bugs that I found while doing the unittests. I will PR when it's done.

**Pull request merged**
