### PR TITLE
Increase speed of nodes nodesExtraction algorithm and apply it in newInstance

### PR DESCRIPTION
**Pull request by igogo-x86**
This version of `nodesExtraction` works 10 times faster than current implementation (See N=20000 at test_ast_deep.py). Also I incorporated the usage of this function in `newInstance` that makes a deep copy of AST node.

I don't see a nice way to make added test fail with specified timeout. Seems like unittests doesn't support it. So this test probably doesn't test a lot (just works for very long time if speed degrades) so may be it should be deleted.

There's still exists the same problem when ascending AST(which is actually a DAG) traversal is happening in `AbstractNode::init` and `AbstractNode::initParents` functions. Current version will be calling the same methods several times for already processed elements and it never finishes when applying triton to real-live obfuscators. In my private version I comment them out but I would like to make the similar to nodesExtraction mechanism. So is it okey if I remove calling `initParent` from all `init` methods and make `initParent` first collecting all depending nodes and applying `init` to them?

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
> I don't see a nice way to make added test fail with specified timeout. Seems like unittests doesn't support it. So this test probably doesn't test a lot (just works for very long time if speed degrades) so may be it should be deleted.

Yes, maybe we can remove this test.

> There's still exists the same problem when ascending AST(which is actually a DAG) traversal is happening in AbstractNode::init and AbstractNode::initParents functions. Current version will be calling the same methods several times for already processed elements and it never finishes when applying triton to real-live obfuscators. In my private version I comment them out but I would like to make the similar to nodesExtraction mechanism. So is it okey if I remove calling initParent from all init methods and make initParent first collecting all depending nodes and applying init to them?

If this is better for performance, yes go ahead! I'm always happy to merge MR which help us to scale on real world programs :)

**Comment by JonathanSalwan** [comment]
mmmh, in fact let's keep this test.

**Comment by JonathanSalwan** [comment]
> There's still exists the same problem when ascending AST(which is actually a DAG) traversal is happening in AbstractNode::init and AbstractNode::initParents functions. Current version will be calling the same methods several times for already processed elements and it never finishes when applying triton to real-live obfuscators. In my private version I comment them out but I would like to make the similar to nodesExtraction mechanism. So is it okey if I remove calling initParent from all init methods and make initParent first collecting all depending nodes and applying init to them?

btw, check out this MR #815 which is, I think, similar to the issue.

**Comment by igogo-x86** [comment]
> mmmh, in fact let's keep this test.

Internet says there's https://pypi.org/project/timeout-decorator/ such a module to make tests with timeout, but I think it's better to avoid unnecessary dependencies.

> btw, check out this MR #815 which is, I think, similar to the issue.

Seems like my commits doesn't interact with it. Am I correct that `processSimplification` is called only for new nodes? So they don't have parent yet and no need to call `initParents` for simplified node

**Comment by igogo-x86** [comment]
Some tests won't pass but looks like it's current branch problems

**Comment by JonathanSalwan** [comment]
> Some tests won't pass but looks like it's current branch problems

I'm not sure this is due to the current branch.

**Comment by JonathanSalwan** [comment]
I've created a branch (`dev-820`) to test this MR. If you can pull it and see what's happen it could be great. I got a crash in the `nodesExtraction` function.

**Pull request merged**
