### PR TITLE
x86 flags semantics fix

### PR DESCRIPTION
**Pull request by Mahorori**
spread taint if symbolized and dont remove from written register

### CODE REVIEW

**Comment by SweetVishnya** [comment]
Seems to be a part of #908.

**Comment by JonathanSalwan** [comment]
> Seems to be a part of #908.

Yep, I will probably merge this PR but maybe this code will be removed if we rewrite the taint analysis.

**Comment by JonathanSalwan** [comment]
Actually, there are some things not really natural for me in this MR:

- If we do that, we have to do the same thing for every conditional instructions.
- It's not really a dynamic taint analysis anymore (taint following the concrete execution).
- What if it's unsat?

**Comment by SweetVishnya** [comment]
I personally don't like checking symbolic state in taint.

**Comment by Mahorori** [comment]
if "x86_cl" register is symbolized and I do processing instruction "shl eax,cl"
I expect cf flag is in writtenRegisters or tainted.

if I understand correctly symbolized != concrete?
not sure about taint engine tbh so maybe it isn't great idea

**Comment by JonathanSalwan** [comment]
`writtenRegisters` defines what registers are really written according to the concrete execution. It not assumes the possibilities of the symbolic reasoning. So, cf will be tainted or tagged as written register if and only if the concrete execution writes into cf.

**Comment by Mahorori** [comment]
hm I see. I guess I had wrong idea of how triton works then.
Probably bad idea for taint analysis yet I think since symbolic expression contains IterNode and It doesn't hurt anything it's not bad to have those in writtenRegisters.
if that's not the way I'll close

**Comment by JonathanSalwan** [comment]
I think we can close this pr. Sorry @Mahorori, but maybe the #908 will fix your issue.

**Pull request closed without merging**
