### PR TITLE
Add API method for pushing path condition object

### PR DESCRIPTION
**Pull request by apach301**
Add API method which allows you to push user-crafted pathCondition to pathManager.

### CODE REVIEW

**Comment by SweetVishnya** [comment]
@JonathanSalwan, we need it to add custom constraints to path predicate.

**Comment by JonathanSalwan** [comment]
Thanks guys,

The patch looks good to me, I will merge it this week.

**Comment by JonathanSalwan** [comment]
However, if you can add a test in this [file](https://github.com/JonathanSalwan/Triton/blob/dev-v0.9/src/examples/cpp/ctest_api.cpp#L467) to check that everything are working like you want, it will help :)

**Comment by apach301** [comment]
@JonathanSalwan, added test_9 to check correctness of pushing custom path condition to the pathManager

**Pull request merged**
