### PR TITLE
Enable to use Python 3.9

### PR DESCRIPTION
**Pull request by romainthomas**

### CODE REVIEW

**Comment by SweetVishnya** [comment]
Can we specify python version as a CMake option? Having a separety option for each Python version seems not to be universal.

**Comment by JonathanSalwan** [comment]
Yeah i think we can do that. Something like `cmake -DPYTHON_VERSION=3.9` with 3.6 as default.

**Comment by SweetVishnya** [comment]
Can u make it?)

**Comment by JonathanSalwan** [comment]
> Can u make it?)

ok, i will.

**Comment by SweetVishnya** [comment]
Thanks)

**Pull request merged**
