### PR TITLE
Check if PYTHON_SITE_PACKAGES is defined

### PR DESCRIPTION
**Pull request by 0poss**
Let the user set a custom `PYTHON_SITE_PACKAGES` instead of `distutils.sysconfig.get_python_libs()`.

### CODE REVIEW

**Comment by 0poss** [comment]
I messed up
Fixing this, making it cleaner and adding the same change to libtriton

**Comment by JonathanSalwan** [comment]
According to 65c9a6e, I think you have to rebase so that you get up-to-date with the current master version.

**Comment by 0poss** [comment]
Too much of a mess, closing and reopening a cleaner one
I'm new to this, apologies

**Comment by JonathanSalwan** [comment]
Hehe np :D

**Pull request closed without merging**
