### PR TITLE
fixed xor taint propagation with same register + added unittest

### LINKED ISSUE #825: taint propagation wrong for "xor reg, reg"
As the title says, the taint propagation is wrong for `xor` if the source and destination register is the same. It should clear the taint since the result of the operation does not depend on the value of the tainted source/destination

Example:
```
eax is tainted
xor eax, eax  # this should clear the taint but it doesn't
eax is tainted
```

### PR DESCRIPTION
**Pull request by Toizi**
fixes #825

### CODE REVIEW

**Comment by JonathanSalwan** [comment]
This is false. Counter example `add rax, rax`.

**Comment by Toizi** [comment]
@JonathanSalwan it doesn't touch `add` though. The if statement is in the `xor_s` function and not in a general taint spreading function

**Comment by JonathanSalwan** [comment]
Arf, I didn't not saw this. I was thinking it was in the taintEngine.cpp. Sorry.

**Comment by JonathanSalwan** [comment]
Let me think about this, because if we do that for the `xor_s` we have to do it for all others instructions... (see https://github.com/JonathanSalwan/Triton/issues/825#issuecomment-548381828)

**Comment by JonathanSalwan** [comment]
btw, I think there is an error if we process the instruction `xor byte ptr [rax], 1`. In this case, I think `src.getRegister()` and `dst.getRegister()` are equal with an invalid register.

**Comment by Toizi** [comment]
Good catch. I didn't realize you can xor memory directly but I'm not surprised since it's x86.

I think my latest commit should fix the issue

**Pull request merged**
